aws_region         = "us-east-1"
s3_bucket_name     = "cognition-inputs"
nasa_api_key       = "YOUR-NASA-API-KEY" # Replace securely for production
opensearch_domain  = "your-opensearch-domain.us-east-1.es.amazonaws.com"
vector_dim         = 768
lambda_memory_size = 512
lambda_timeout     = 60
meta_index        = "humanai-meta"
dream_lambda_url  = "https://your-api-gateway-id.execute-api.us-east-1.amazonaws.com/prod/trigger-dream"
